### ISSUE TITLE
_ notation

### ISSUE THREAD

**Issue by admwx7** [screendriver/plugin-sass#10]
As it turns out, SASS supports importing files without _ that the file name actually contains an _, for example, the bootstrap-sass project uses `@import "bootstrap/variables";` where the actual file name is `.../_variables.scss`, when running a compile through sass itself this works out fine, however it fails through JSPM, if I change the import to `@import "bootstrap/_variables";` it will succeed though.

**Comment by screendriver** [comment]
Hi @admwx7,

thank you for the report. I will look into this.

**Comment by phenomnomnominal** [comment]
I believe my pull request fixed this.

**Comment by screendriver** [comment]
I believe that too. Pull request #12 fixes this issue. Feel free to report a new bug report if something is still not working.
