### ISSUE TITLE
URLs are referenced relative to the document not the file

### ISSUE THREAD

**Issue by guybedford** [screendriver/plugin-sass#2]
For example:

```
{
  background: url(./test.jpg);
}
```

In a file at `app/test.sass`.

Will attempt to load `/test.jpg` instead of `/app/test.jpg`.

Sass imports are working ok from what I can tell though.

**Comment by screendriver** [comment]
Thank you for the report. I will look into that.

**Comment by screendriver** [comment]
Should hopefully be fixed now. Please let me know if the issue still exist.
