### ISSUE TITLE
sass-inject.js not found

### ISSUE THREAD

**Issue by teddybradford** [screendriver/plugin-sass#4]
I am getting the following error when trying to import a scss file:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:1 Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost:4444/sass-inject.js(…)
```

**Comment by screendriver** [comment]
Can you provide me more information? For example a [Gist](https://gist.github.com) or a sample project or something?
Do the the tests mentioned in the readme run on your machine?

**Comment by teddybradford** [comment]
Your tests work on my machine. I put together a bare-bones couple of files that should hopefully replicate the error I'm getting: https://gist.github.com/teddybradford/4ff91b1ba91f2c736aaa
My guess is that it may have to do with BrowserSync script, but I don't see any reason why it would be affecting this.

**Comment by screendriver** [comment]
Thank you very much. I fixed it and made a `v0.0.4` release.

**Comment by teddybradford** [comment]
Awesome, it's working now in my other project. Thanks for the quick update! :)

**Comment by screendriver** [comment]
You're welcome :sunglasses:
