### ISSUE TITLE
Fetch API cannot load 'file' url scheme.

### ISSUE THREAD

**Issue by f15gdsy** [screendriver/plugin-sass#6]
Hi, thanks for the plugin! It looks great!
I want to use it with Electron and the files are using 'file' url scheme, like 'file://'.
But Fetch API does not support it.
It would be great if file url scheme is supported :)

**Comment by screendriver** [comment]
Hi @f15gdsy,
thank you for using the plugin. There is already a reported bug in the https://github.com/github/fetch/issues/91 repo about that. Maybe you hook in there?

**Comment by f15gdsy** [comment]
Thanks for your reply!
There seems to be [pull request](https://github.com/github/fetch/pull/92) to handle this issue already but there is no signs that the author is going to merge it.
But anyway thank you very much :)
